### ISSUE TITLE
Pulling multiple copies of cards with single and double faced versions

### ISSUE THREAD

**Issue by metalman42** [crookedneighbor/mana-tithe#23]
Cards that appeared in the "Heads I win Tails you Lose" secret lair are pulling both the cheapest version of the single faced card and the secret lair version. I found this issue with the following cards:
1     Okaun, Eye of Chaos
1     Zndrsplt, Eye of Wisdom
1     Krark's Thumb
1     Stitch in Time

I received this output:
1	Krark's Thumb	$10.06
1	Krark's Thumb // Krark's Thumb	$26.50
1	Okaun, Eye of Chaos	$1.13
1	Okaun, Eye of Chaos // Okaun, Eye of Chaos	$16.00
1	Stitch in Time	$4.60
1	Stitch in Time // Stitch in Time	$20.00
1	Zndrsplt, Eye of Wisdom	$1.16
1	Zndrsplt, Eye of Wisdom // Zndrsplt, Eye of Wisdom	$18.93

**Comment by crookedneighbor** [comment]
Thanks for finding this. I've pushed up a fix, should be deployed to the site in the next 20 minutes or so.
